#include <iostream>
#include <unordered_map>
#include <string>
#include <vector>
#include <utility>
using namespace std;
#include <sstream>

struct TrieNode {
    unordered_map<char, TrieNode*> children;
    bool isEndOfWord;
    TrieNode() : isEndOfWord(false) {}
};

class Trie {
private:
    TrieNode* root;
public:
    Trie() { root = new TrieNode(); }
    void insert(const string& word) {
        TrieNode* node = root;
        for (char c : word) {
            if (node->children.find(c) == node->children.end()) {
                node->children[c] = new TrieNode();
            }
            node = node->children[c];
        }
        node->isEndOfWord = true;
    }
    vector<string> autocomplete(const string& prefix);
    pair<bool, vector<string>> spellCheck(const string& word);
    bool search(const string& word) const {
        TrieNode* node = root;
        for (char c : word) {
            auto it = node->children.find(c);
            if (it == node->children.end()) return false;
            node = it->second;
        }
        return node->isEndOfWord;
    }
    void remove(const string& word) {
        deleteHelper(root, word, 0);
    }
private:
    bool deleteHelper(TrieNode* node, const string& word, int index) {
        if (!node) return false;
        if (index == (int)word.size()) {
            if (!node->isEndOfWord) return false;
            node->isEndOfWord = false;
            return node->children.empty();
        }
        char c = word[index];
        auto it = node->children.find(c);
        if (it == node->children.end()) return false;
        TrieNode* child = it->second;
        bool shouldDelete = deleteHelper(child, word, index + 1);
        if (shouldDelete) {
            delete child;
            node->children.erase(c);
        }
        return !node->isEndOfWord && node->children.empty();
    }
    void collectWords(TrieNode* node, const string& current, vector<string>& words);
    int countWordsHelper(TrieNode* node);
};

void Trie::collectWords(TrieNode* node, const string& current, vector<string>& words) {
    if (node->isEndOfWord) words.push_back(current);
    for (auto& p : node->children) {
        collectWords(p.second, current + p.first, words);
    }
}

int Trie::countWordsHelper(TrieNode* node) {
    int count = node->isEndOfWord ? 1 : 0;
    for (auto& p : node->children) {
        count += countWordsHelper(p.second);
    }
    return count;
}

vector<string> Trie::autocomplete(const string& prefix) {
    TrieNode* node = root;
    for (char c : prefix) {
        auto it = node->children.find(c);
        if (it == node->children.end()) return {};
        node = it->second;
    }
    vector<string> words;
    collectWords(node, prefix, words);
    return words;
}

int countOccurrences(const string& text, const string& pattern) {
    int count = 0;
    size_t pos = 0;
    while ((pos = text.find(pattern, pos)) != string::npos) {
        ++count;
        pos += 1;
    }
    return count;
}

pair<bool, vector<string>> Trie::spellCheck(const string& word) {
    bool found = search(word);
    vector<string> suggestions;
    if (!found) {
        string prefix = "";
        TrieNode* node = root;
        for (char c : word) {
            auto it = node->children.find(c);
            if (it == node->children.end()) break;
            prefix += c;
            node = it->second;
        }
        if (!prefix.empty()) {
            suggestions = autocomplete(prefix);
        }
    }
    return {found, suggestions};
}

int main() {
    Trie trie;
    // Pre-insert some words
    trie.insert("apple");
    trie.insert("app");
    trie.insert("banana");
    trie.insert("application");
    trie.insert("apply");
    trie.insert("functional");
    trie.insert("herald");
    trie.insert("somewhere");
    trie.insert("bush");
    trie.insert("webster");
    trie.insert("lies");
    trie.insert("savage");
    trie.insert("paraguay");
    trie.insert("legend");
    trie.insert("matters");
    trie.insert("qualities");
    trie.insert("destroyed");
    trie.insert("kong");
    trie.insert("bug");
    trie.insert("automatically");
    trie.insert("goto");
    trie.insert("your");
    trie.insert("resolution");
    trie.insert("delivery");
    trie.insert("pregnancy");
    trie.insert("eyed");
    trie.insert("montreal");
    trie.insert("joke");
    trie.insert("pn");
    trie.insert("settlement");
    trie.insert("brief");
    trie.insert("loan");
    trie.insert("logitech");
    trie.insert("produce");
    trie.insert("rpg");
    trie.insert("sage");
    trie.insert("revision");
    trie.insert("stuff");
    trie.insert("routine");
    trie.insert("pokemon");
    trie.insert("mistress");
    trie.insert("cherry");
    trie.insert("elsewhere");
    trie.insert("bbc");
    trie.insert("vitamins");
    trie.insert("superb");
    trie.insert("holmes");
    trie.insert("holly");
    trie.insert("quest");
    trie.insert("any");
    trie.insert("mercury");
    trie.insert("melbourne");
    trie.insert("forum");
    trie.insert("qc");
    trie.insert("reaction");
    trie.insert("handy");
    trie.insert("fantasy");
    trie.insert("cluster");
    trie.insert("assure");
    trie.insert("percentage");
    trie.insert("friday");
    trie.insert("accordance");
    trie.insert("gore");
    trie.insert("employee");
    trie.insert("threats");
    trie.insert("guild");
    trie.insert("warming");
    trie.insert("thriller");
    trie.insert("informal");
    trie.insert("cingular");
    trie.insert("calendar");
    trie.insert("associates");
    trie.insert("towers");
    trie.insert("marilyn");
    trie.insert("ir");
    trie.insert("creativity");
    trie.insert("iv");
    trie.insert("placement");
    trie.insert("awareness");
    trie.insert("lender");
    trie.insert("useful");
    trie.insert("awards");
    trie.insert("grad");
    trie.insert("connected");
    trie.insert("troy");
    trie.insert("bio");
    trie.insert("applicants");
    trie.insert("connectors");
    trie.insert("italian");
    trie.insert("stayed");
    trie.insert("library");
    trie.insert("place");
    trie.insert("composite");
    trie.insert("ambien");
    trie.insert("powder");
    trie.insert("published");
    trie.insert("doe");
    trie.insert("signature");
    trie.insert("gather");
    trie.insert("appears");
    trie.insert("had");
    trie.insert("blocks");
    trie.insert("resulting");
    trie.insert("penguin");
    trie.insert("metadata");
    trie.insert("predictions");
    trie.insert("lodging");
    trie.insert("commonwealth");
    trie.insert("coastal");
    trie.insert("jersey");
    trie.insert("town");
    trie.insert("impression");
    trie.insert("permalink");
    trie.insert("acts");
    trie.insert("scenario");
    trie.insert("raid");
    trie.insert("ce");
    trie.insert("monitors");
    trie.insert("continuously");
    trie.insert("laws");
    trie.insert("ban");
    trie.insert("naturals");
    trie.insert("lasting");
    trie.insert("alberta");
    trie.insert("roberts");
    trie.insert("catering");
    trie.insert("favorites");
    trie.insert("realized");
    trie.insert("defendant");
    trie.insert("suggest");
    trie.insert("wash");
    trie.insert("applied");
    trie.insert("majority");
    trie.insert("bars");
    trie.insert("reflects");
    trie.insert("consistently");
    trie.insert("exp");
    trie.insert("cents");
    trie.insert("blue");
    trie.insert("loss");
    trie.insert("eliminate");
    trie.insert("placed");
    trie.insert("mysql");
    trie.insert("austin");
    trie.insert("merger");
    trie.insert("composition");
    trie.insert("isle");
    trie.insert("genres");
    trie.insert("candle");
    trie.insert("beast");
    trie.insert("bride");
    trie.insert("referenced");
    trie.insert("depth");
    trie.insert("community");
    trie.insert("counts");
    trie.insert("buried");
    trie.insert("characters");
    trie.insert("ellen");
    trie.insert("accessible");
    trie.insert("pierce");
    trie.insert("society");
    trie.insert("searchcom");
    trie.insert("errors");
    trie.insert("narrow");
    trie.insert("pee");
    trie.insert("hi");
    trie.insert("sexcam");
    trie.insert("contracts");
    trie.insert("immigration");
    trie.insert("three");
    trie.insert("shapes");
    trie.insert("shows");
    trie.insert("jail");
    trie.insert("complicated");
    trie.insert("pet");
    trie.insert("ten");
    trie.insert("rounds");
    trie.insert("observed");
    trie.insert("related");
    trie.insert("cope");
    trie.insert("chad");
    trie.insert("jpg");
    trie.insert("plugins");
    trie.insert("dns");
    trie.insert("gps");
    trie.insert("downloadcom");
    trie.insert("retro");
    trie.insert("malawi");
    trie.insert("headlines");
    trie.insert("slides");
    trie.insert("logistics");
    trie.insert("points");
    trie.insert("bunch");
    trie.insert("malaysia");
    trie.insert("troubleshooting");
    trie.insert("qualifications");
    trie.insert("colors");
    trie.insert("oregon");
    trie.insert("listing");
    trie.insert("previously");
    trie.insert("realtors");
    trie.insert("recreational");
    trie.insert("ping");
    trie.insert("creatures");
    trie.insert("motorcycles");
    trie.insert("stage");
    trie.insert("prophet");
    trie.insert("adam");
    trie.insert("ds");
    trie.insert("cnet");
    trie.insert("material");
    trie.insert("gamma");
    trie.insert("plastic");
    trie.insert("round");
    trie.insert("organized");
    trie.insert("crowd");
    trie.insert("plants");
    trie.insert("host");
    trie.insert("clearing");
    trie.insert("looks");
    trie.insert("specify");
    trie.insert("sega");
    trie.insert("signed");
    trie.insert("lion");
    trie.insert("borough");
    trie.insert("timing");
    trie.insert("textiles");
    trie.insert("calculate");
    trie.insert("butter");
    trie.insert("su");
    trie.insert("ps");
    trie.insert("jenny");
    trie.insert("attractive");
    trie.insert("velocity");
    trie.insert("entering");
    trie.insert("postal");
    trie.insert("every");
    trie.insert("refresh");
    trie.insert("pest");
    trie.insert("dallas");
    trie.insert("indicators");
    trie.insert("venue");
    trie.insert("cutting");
    trie.insert("hans");
    trie.insert("ty");
    trie.insert("twist");
    trie.insert("bin");
    trie.insert("scientists");
    trie.insert("scheme");
    trie.insert("chelsea");
    trie.insert("assembled");
    trie.insert("utah");
    trie.insert("secretary");
    trie.insert("rain");
    trie.insert("congress");
    trie.insert("gift");
    trie.insert("premier");
    trie.insert("arnold");
    trie.insert("speeches");
    trie.insert("adds");
    trie.insert("corresponding");
    trie.insert("survey");
    trie.insert("controller");
    trie.insert("devon");
    trie.insert("carb");
    trie.insert("beside");
    trie.insert("jpeg");
    trie.insert("hd");
    trie.insert("implementation");
    trie.insert("students");
    trie.insert("consoles");
    trie.insert("bleeding");
    trie.insert("tulsa");
    trie.insert("seats");
    trie.insert("induced");
    trie.insert("samoa");
    trie.insert("mtv");
    trie.insert("wins");
    trie.insert("first");
    trie.insert("kentucky");
    trie.insert("biographies");
    trie.insert("asset");
    trie.insert("disclaimers");
    trie.insert("planned");
    trie.insert("wiring");
    trie.insert("jose");
    trie.insert("utilization");
    trie.insert("mass");
    trie.insert("cup");
    trie.insert("certainly");
    trie.insert("enjoy");
    trie.insert("moreover");
    trie.insert("parties");
    trie.insert("naked");
    trie.insert("eden");
    trie.insert("springs");
    trie.insert("theoretical");
    trie.insert("copyright");
    trie.insert("conviction");
    trie.insert("doors");
    trie.insert("edwards");
    trie.insert("transsexual");
    trie.insert("guinea");
    trie.insert("but");
    trie.insert("quantum");
    trie.insert("acne");
    trie.insert("barcelona");
    trie.insert("basically");
    trie.insert("nike");
    trie.insert("without");
    trie.insert("equipment");
    trie.insert("russell");
    trie.insert("wyoming");
    trie.insert("richards");
    trie.insert("interpreted");
    trie.insert("stockholm");
    trie.insert("bookstore");
    trie.insert("chronicle");
    trie.insert("zope");
    trie.insert("blackberry");
    trie.insert("civic");
    trie.insert("corrected");
    trie.insert("ease");
    trie.insert("mins");
    trie.insert("accounts");
    trie.insert("laugh");
    trie.insert("search");
    trie.insert("magnitude");
    trie.insert("hoped");
    trie.insert("cooked");
    trie.insert("mariah");
    trie.insert("predicted");
    trie.insert("largely");
    trie.insert("sociology");
    trie.insert("marvel");
    trie.insert("live");
    trie.insert("fairy");
    trie.insert("produced");
    trie.insert("stadium");
    trie.insert("sufficiently");
    trie.insert("seq");
    trie.insert("farm");
    trie.insert("benz");
    trie.insert("dave");
    trie.insert("oecd");
    trie.insert("expanded");
    trie.insert("enclosure");
    trie.insert("brochures");
    trie.insert("driven");
    trie.insert("clan");
    trie.insert("grows");
    trie.insert("rising");
    trie.insert("sometimes");
    trie.insert("causes");
    trie.insert("prediction");
    trie.insert("aol");
    trie.insert("appointed");
    trie.insert("economies");
    trie.insert("target");
    trie.insert("harley");
    trie.insert("exhibitions");
    trie.insert("profit");
    trie.insert("spot");
    trie.insert("chief");
    trie.insert("involves");
    trie.insert("jury");
    trie.insert("twenty");
    trie.insert("ordinary");
    trie.insert("berry");
    trie.insert("advocate");
    trie.insert("undo");
    trie.insert("licence");
    trie.insert("camera");
    trie.insert("active");
    trie.insert("tn");
    trie.insert("worship");
    trie.insert("disable");
    trie.insert("amber");
    trie.insert("benefit");
    trie.insert("scotland");
    trie.insert("bicycle");
    trie.insert("slight");
    trie.insert("estimate");
    trie.insert("finds");
    trie.insert("posts");
    trie.insert("expenditures");
    trie.insert("definition");
    trie.insert("yo");
    trie.insert("receives");
    trie.insert("magnetic");
    trie.insert("declaration");
    trie.insert("popular");
    trie.insert("andorra");
    trie.insert("configure");
    trie.insert("improvement");
    trie.insert("dennis");
    trie.insert("specifications");
    trie.insert("anniversary");
    trie.insert("hits");
    trie.insert("opposite");
    trie.insert("vary");
    trie.insert("byte");
    trie.insert("gateway");
    trie.insert("son");
    trie.insert("tight");
    trie.insert("nest");
    trie.insert("sauce");
    trie.insert("probability");
    trie.insert("judge");
    trie.insert("subaru");
    trie.insert("karen");
    trie.insert("enjoyed");
    trie.insert("imperial");
    trie.insert("webmaster");
    trie.insert("releases");
    trie.insert("pork");
    trie.insert("ultram");
    trie.insert("monster");
    trie.insert("domain");
    trie.insert("balanced");
    trie.insert("declare");
    trie.insert("possess");
    trie.insert("ga");
    trie.insert("mention");
    trie.insert("transport");
    trie.insert("origins");
    trie.insert("automation");
    trie.insert("spider");
    trie.insert("olympic");
    trie.insert("sea");
    trie.insert("slot");
    trie.insert("burke");
    trie.insert("conferences");
    trie.insert("attract");
    trie.insert("comics");
    trie.insert("accounting");
    trie.insert("urgent");
    trie.insert("calculations");
    trie.insert("dt");
    trie.insert("denied");
    trie.insert("ed");
    trie.insert("preston");
    trie.insert("optimum");
    trie.insert("memphis");
    trie.insert("cornwall");
    trie.insert("oxide");
    trie.insert("toolbox");
    trie.insert("validation");
    trie.insert("upgrading");
    trie.insert("infectious");
    trie.insert("precisely");
    trie.insert("seen");
    trie.insert("robust");
    trie.insert("promotion");
    trie.insert("photo");
    trie.insert("exhibit");
    trie.insert("applicable");
    trie.insert("groove");
    trie.insert("vendors");
    trie.insert("keep");
    trie.insert("era");
    trie.insert("detail");
    trie.insert("epa");
    trie.insert("productive");
    trie.insert("friends");
    trie.insert("polar");
    trie.insert("rankings");
    trie.insert("tournament");
    trie.insert("laden");
    trie.insert("messages");
    trie.insert("tools");
    trie.insert("matched");
    trie.insert("associations");
    trie.insert("av");
    trie.insert("bermuda");
    trie.insert("auckland");
    trie.insert("mitsubishi");
    trie.insert("obituaries");
    trie.insert("prohibited");
    trie.insert("sink");
    trie.insert("florida");
    trie.insert("undertake");
    trie.insert("font");
    trie.insert("sue");
    trie.insert("wanted");
    trie.insert("vault");
    trie.insert("donor");
    trie.insert("imagine");
    trie.insert("liabilities");
    trie.insert("proudly");
    trie.insert("compensation");
    trie.insert("automotive");
    trie.insert("suggesting");
    trie.insert("her");
    trie.insert("aerial");
    trie.insert("crazy");
    trie.insert("meet");
    trie.insert("compared");
    trie.insert("bills");
    trie.insert("levy");
    trie.insert("helping");
    trie.insert("pete");
    trie.insert("attorney");
    trie.insert("subtle");
    trie.insert("palestinian");
    trie.insert("feb");
    trie.insert("accident");
    trie.insert("modular");
    trie.insert("critics");
    trie.insert("charge");
    trie.insert("all");
    trie.insert("wrapping");
    trie.insert("classes");
    trie.insert("heart");
    trie.insert("electrical");
    trie.insert("indoor");
    trie.insert("prospective");
    trie.insert("publish");
    trie.insert("much");
    trie.insert("extremely");
    trie.insert("reproductive");
    trie.insert("tire");
    trie.insert("format");
    trie.insert("official");
    trie.insert("plane");
    trie.insert("cure");
    trie.insert("cancelled");
    trie.insert("debt");
    trie.insert("cons");
    trie.insert("privacy");
    trie.insert("obtain");
    trie.insert("precious");
    trie.insert("belly");
    trie.insert("declined");
    trie.insert("message");
    trie.insert("assign");
    trie.insert("spam");
    trie.insert("assume");
    trie.insert("ultimate");
    trie.insert("checkout");
    trie.insert("founded");
    trie.insert("strict");
    trie.insert("placing");
    trie.insert("adaptive");
    trie.insert("squirting");
    trie.insert("airport");
    trie.insert("registration");
    trie.insert("isa");
    trie.insert("rangers");
    trie.insert("celebrities");
    trie.insert("consent");
    trie.insert("cbs");
    trie.insert("violent");
    trie.insert("webpage");
    trie.insert("responding");
    trie.insert("sensors");
    trie.insert("folk");
    trie.insert("workplace");
    trie.insert("words");
    trie.insert("who");
    trie.insert("lonely");
    trie.insert("randy");
    trie.insert("ana");
    trie.insert("sphere");
    trie.insert("farmer");
    trie.insert("disney");
    trie.insert("deadline");
    trie.insert("indicate");
    trie.insert("runtime");
    trie.insert("effect");
    trie.insert("dispute");
    trie.insert("charged");
    trie.insert("stewart");
    trie.insert("rocky");
    trie.insert("foot");
    trie.insert("support");
    trie.insert("navigator");
    trie.insert("revolutionary");
    trie.insert("vision");
    trie.insert("gains");
    trie.insert("restaurants");
    trie.insert("variance");
    trie.insert("bryant");
    trie.insert("regulatory");
    trie.insert("sussex");
    trie.insert("moss");
    trie.insert("dylan");
    trie.insert("clinic");
    trie.insert("investors");
    trie.insert("buck");
    trie.insert("heat");
    trie.insert("toronto");
    trie.insert("harry");
    trie.insert("candy");
    trie.insert("anime");
    trie.insert("royalty");
    trie.insert("syracuse");
    trie.insert("handjobs");
    trie.insert("divine");
    trie.insert("knowledgestorm");
    trie.insert("reload");
    trie.insert("ontario");
    trie.insert("employees");
    trie.insert("patrick");
    trie.insert("collecting");
    trie.insert("mount");
    trie.insert("fault");
    trie.insert("wants");
    trie.insert("textbooks");
    trie.insert("feat");
    trie.insert("march");
    trie.insert("ensure");
    trie.insert("postings");
    trie.insert("charms");
    trie.insert("lead");
    trie.insert("cf");
    trie.insert("coral");
    trie.insert("marking");
    trie.insert("icq");
    trie.insert("squad");
    trie.insert("lesbian");
    trie.insert("defensive");
    trie.insert("gross");
    trie.insert("graph");
    trie.insert("pastor");
    trie.insert("bradley");
    trie.insert("growing");
    trie.insert("intensity");
    trie.insert("ruled");
    trie.insert("misc");
    trie.insert("spyware");
    trie.insert("campbell");
    trie.insert("hazards");
    trie.insert("coming");
    trie.insert("balance");
    trie.insert("likewise");
    trie.insert("move");
    trie.insert("contractors");
    trie.insert("lighter");
    trie.insert("classifieds");
    trie.insert("scheduling");
    trie.insert("spaces");
    trie.insert("potential");
    trie.insert("sucking");
    trie.insert("outdoors");
    trie.insert("gamecube");
    trie.insert("ted");
    trie.insert("disclose");
    trie.insert("variety");
    trie.insert("boat");
    trie.insert("art");
    trie.insert("zdnet");
    trie.insert("internship");
    trie.insert("festival");
    trie.insert("pools");
    trie.insert("mrs");
    trie.insert("spanish");
    trie.insert("estate");
    trie.insert("justin");
    trie.insert("kijiji");
    trie.insert("supplied");
    trie.insert("mobile");
    trie.insert("me");
    trie.insert("personally");
    trie.insert("vast");
    trie.insert("fence");
    trie.insert("everyday");
    trie.insert("bandwidth");
    trie.insert("young");
    trie.insert("lips");
    trie.insert("embassy");
    trie.insert("camping");
    trie.insert("submissions");
    trie.insert("break");
    trie.insert("gnome");
    trie.insert("forth");
    trie.insert("swiss");
    trie.insert("marks");
    trie.insert("memories");
    trie.insert("pure");
    trie.insert("dust");
    trie.insert("yours");
    trie.insert("female");
    trie.insert("funds");
    trie.insert("riverside");
    trie.insert("mission");
    trie.insert("lost");
    trie.insert("chinese");
    trie.insert("bench");
    trie.insert("teenage");
    trie.insert("range");
    trie.insert("micro");
    trie.insert("coordination");
    trie.insert("chem");
    trie.insert("passwords");
    trie.insert("pentium");
    trie.insert("sort");
    trie.insert("watched");
    trie.insert("jake");
    trie.insert("symptoms");
    trie.insert("playlist");
    trie.insert("response");
    trie.insert("nobody");
    trie.insert("enters");
    trie.insert("offer");

    cout << boolalpha;
    while (true) {
        cout << "\nTrie Operations Menu:" << endl;
        cout << "1. Insert a word" << endl;
        cout << "2. Search for a word" << endl;
        cout << "3. Delete a word" << endl;
        cout << "4. Autocomplete" << endl;
        cout << "5. Count words with prefix" << endl;
        cout << "6. Spell check" << endl;
        cout << "7. Quit" << endl;
        cout << "Enter your choice (1-7): ";
        int choice;
        cin >> choice;
        cin.ignore(); // Ignore newline

        if (choice == 1) {
            cout << "Enter word to insert: ";
            string word;
            getline(cin, word);
            trie.insert(word);
            cout << "Inserted: " << word << endl;
        } else if (choice == 2) {
            cout << "Enter word to search: ";
            string word;
            getline(cin, word);
            cout << "Found: " << trie.search(word) << endl;
        } else if (choice == 3) {
            cout << "Enter word to delete: ";
            string word;
            getline(cin, word);
            trie.remove(word);
            cout << "Deleted: " << word << endl;
        } else if (choice == 4) {
            cout << "Enter prefix for autocomplete: ";
            string prefix;
            getline(cin, prefix);
            auto words = trie.autocomplete(prefix);
            cout << "Suggestions: ";
            for (auto& w : words) cout << w << " ";
            cout << endl;
        } else if (choice == 5) {
            cout << "Enter word: ";
            string word;
            getline(cin, word);
            cout << "Enter prefix to count: ";
            string prefix;
            getline(cin, prefix);
            cout << "Count: " << countOccurrences(word, prefix) << endl;
        } else if (choice == 6) {
            cout << "Enter word to spell check: ";
            string word;
            getline(cin, word);
            auto result = trie.spellCheck(word);
            if (result.first) {
                cout << "'" << word << "' is spelled correctly." << endl;
            } else {
                cout << "'" << word << "' is misspelled. Suggestions: ";
                for (auto& s : result.second) cout << s << " ";
                cout << endl;
                // Optionally, offer to insert a suggestion
                if (!result.second.empty()) {
                    cout << "Would you like to insert '" << result.second[0] << "'? (y/n): ";
                    char yn;
                    cin >> yn;
                    cin.ignore();
                    if (yn == 'y' || yn == 'Y') {
                        trie.insert(result.second[0]);
                        cout << "Inserted: " << result.second[0] << endl;
                    }
                }
            }
        } else if (choice == 7) {
            break;
        } else {
            cout << "Invalid choice. Try again." << endl;
        }
    }
    return 0;
}